#!/bin/sh

###################
# Set JDK 1.7 as the default
# export JAVA_HOME=`/usr/libexec/java_home -v 1.7`

###################
# Set textmate as our default command line editor
#export EDITOR='mate -w'
# Set Sublime as our default command line editor
export EDITOR='subl'

# Setup Maven environment (M2_HOME & M2 are setup through MacOSX defaults)
export MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=512m"

# Setup JAVA environment
export JAVA_OPTS="-Xms256m -Xmx2048m -XX:MaxPermSize=512m"

# Setup Oracle environment
export ORACLE_ROOT=/Applications/oracle
export ORACLE_HOME=$ORACLE_ROOT/client/11.2.0
export TNS_ADMIN=$ORACLE_ROOT/admin/network
export DYLD_LIBRARY_PATH=$ORACLE_HOME/lib
